// ============================================================
// MAQNA.ID — Shared Tour Data
// Used by all tour pages (turkey, new-zealand, serbia, etc.)
// ============================================================

const WA_NUMBER = '628164610513';
const WA_BASE = `https://wa.me/${WA_NUMBER}`;
const EMAIL = 'maqna.ind@gmail.com';
const CDN = 'https://cdn.jsdelivr.net/gh/dzakanuralam/maqna/images/';

const TOURS = {
    turkiye: {
        slug: 'turkey',
        metaTitle: 'Turkiye Islamic Civilization Tour — Maqna.ID',
        metaDesc: 'Explore the legacy of the Ottoman Empire and Sultan Muhammad Al-Fatih. 10-day meaningful journey through Istanbul, Bursa, Edirne, Cappadocia & more.',
        category: 'international',
        badge: 'Featured Journey',
        image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=1200&auto=format&fit=crop&q=80',
        imgAlt: 'Istanbul Turkiye Blue Mosque',
        duration: '10 Days · 7 Nights',
        dest: 'Turkiye · 10 Days 7 Nights',
        title: 'Islamic Civilization Tour',
        sub: 'Türkiye',
        desc: 'Explore the legacy of the Ottoman Empire and the extraordinary leadership of Sultan Muhammad Al-Fatih. Journey through Islamic governance and the historic conquest of Constantinople.',
        highlights: ['Hagia Sophia', 'Topkapi Palace', 'Bosphorus Cruise', 'Blue Mosque', 'Bursa Ottoman Heritage', 'Cappadocia', 'Selimiye Mosque', 'Fatih Mosque'],
        includes: ['International flight tickets via Emirates / Qatar / Etihad', 'Baggage allowance: 25kg check-in & 7kg cabin', 'Accommodation in 4/5-star hotels', 'Transportation by tour bus throughout the trip', 'Full board meals as per itinerary', 'Tours & entrance tickets to attractions', '1 bottle of mineral water per person per day', 'Bosphorus Cruise in Istanbul', 'Turkish tour guide (Indonesian-speaking)', 'Tour leader from Indonesia', 'Airport handling in Jakarta (Departure)'],
        info: [{ label: 'Duration', value: '10 Days' }, { label: 'Nights', value: '7 Nights' }, { label: 'Destination', value: 'Türkiye' }, { label: 'Seasons', value: 'Winter · Spring · Autumn' }],
        route: [
            { name: 'Edirne', desc: 'Selimiye Mosque, Beyazid II Health Museum & Ottoman heritage journey' },
            { name: 'Istanbul', desc: 'Abu Ayyub Al Ansari Mosque, Pierre Loti & Panorama 1453' },
            { name: 'İznik', desc: 'Historic İznik Hagia Sophia & the iconic Özbek Mosque' },
            { name: 'Bursa', desc: 'Ulu Cami, Koza Han & the tombs of Osman Gazi and Orhan Gazi' },
            { name: 'Cappadocia', desc: 'Göreme Panorama, Underground City & optional Hot Air Balloon experience' },
            { name: 'Ankara', desc: 'Scenic Salt Lake stop on the journey back to Istanbul' },
            { name: 'Istanbul', desc: 'Blue Mosque, Hagia Sophia, Topkapi Palace & Fatih Mosque' },
        ],
        waMsg: "Assalamu'alaikum%20Maqna.ID%2C%20saya%20tertarik%20paket%20Turkiye",
        emailSubject: 'Inquiry: Turkiye Tour',
        itinerary: 'https://cdn.jsdelivr.net/gh/dzakanuralam/maqna/images/Ottoman%20Heritage%20Journey.pdf',
    },
    nz: {
        slug: 'new-zealand',
        metaTitle: 'New Zealand Islamicity Index Journey — Maqna.ID',
        metaDesc: 'Explore New Zealand as one of the world\'s top Islamicity Index countries. 7-day meaningful journey through Auckland, Rotorua, Waitomo & more.',
        category: 'international',
        badge: 'Islamicity Journey',
        image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=1200&auto=format&fit=crop&q=80',
        imgAlt: 'New Zealand North Island landscape',
        duration: '7 Days · 6 Nights',
        dest: 'New Zealand · 7 Days 6 Nights',
        title: 'Islamicity Index Journey',
        sub: 'Maori Muslim Communities',
        desc: 'A meaningful journey exploring New Zealand as one of the world\'s top Islamicity Index countries — reflecting Islamic values of justice, cleanliness, tolerance, and social harmony.',
        highlights: ['Auckland City & Islamic Community', 'Maori Muslim Community', 'Rotorua Cultural Village', 'Waitomo Glowworm Cave', 'Lake Taupo', 'Hobbiton Movie Set', 'Islamic Values Sessions', 'Nature Tafakkur Sessions'],
        includes: ['Return flights Jakarta–Auckland–Jakarta', '6 nights hotel accommodation', 'Full board halal meals throughout', 'Professional Maqna.ID guide & program', 'All entrance fees & transport', 'Islamic Values Sessions'],
        info: [{ label: 'Duration', value: '7 Days' }, { label: 'Nights', value: '6 Nights' }, { label: 'Destination', value: 'New Zealand' }, { label: 'Seasons', value: 'Winter · Spring · Autumn' }],
        route: [
            { name: 'Auckland', desc: 'City exploration, Winter Garden, Islamic community visit, harbour views' },
            { name: 'Waitomo', desc: 'Glowworm Caves — natural wonder & reflection' },
            { name: 'Rotorua', desc: 'Cultural village, Wai-O-Tapu geothermal & Maori interaction' },
            { name: 'Lake Taupo', desc: 'Volcanic lake landscapes & reflection sessions' },
            { name: 'Hobbiton & Tongariro', desc: 'Shire film set & volcanic national park exploration' },
        ],
        waMsg: "Assalamu'alaikum%20Maqna.ID%2C%20saya%20tertarik%20paket%20New%20Zealand",
        emailSubject: 'Inquiry: New Zealand Tour',
    },
    serbia: {
        slug: 'serbia',
        metaTitle: 'Serbia Islamic History Journey — Maqna.ID',
        metaDesc: 'Discover Islamic heritage in Eastern Europe through the Ottoman Empire legacy. 9-day journey through Istanbul, Belgrade, Novi Sad & Novi Pazar.',
        category: 'international',
        badge: 'Islamic History',
        image: 'https://images.unsplash.com/photo-1555990793-da11153b2473?w=1200&auto=format&fit=crop&q=80',
        imgAlt: 'Belgrade Serbia Kalemegdan Fortress',
        duration: '9 Days · 7 Nights',
        dest: 'Serbia · 9 Days 7 Nights',
        title: 'Islamic History Journey',
        sub: 'Sultan Sulaiman Al-Kanuni',
        desc: 'Discover Islamic heritage in Eastern Europe through the enduring influence of the Ottoman Empire. Explore history, culture, and the inspiring legacy of Islamic leadership in the Balkans.',
        highlights: ['Belgrade Kalemegdan Fortress', 'Novi Sad Ottoman Legacy', 'Novi Pazar Islamic Heart', 'Stari Ras UNESCO Heritage', 'Ottoman Mosques Trail', 'Serbian Muslim Community', 'Historical Sessions', 'Balkan Culinary Experience'],
        includes: ['Return flights Jakarta–Belgrade–Jakarta', '7 nights hotel accommodation', 'Full board halal meals throughout', 'Professional historian & Maqna.ID guide', 'All entrance fees & transport', 'Travel insurance coverage'],
        info: [{ label: 'Duration', value: '9 Days' }, { label: 'Nights', value: '7 Nights' }, { label: 'Destination', value: 'Serbia' }, { label: 'Seasons', value: 'Winter · Spring · Autumn' }],
        route: [
            { name: 'Istanbul', desc: 'Transit & brief exploration of Ottoman legacy' },
            { name: 'Belgrade', desc: 'Kalemegdan Fortress, Islamic heritage trail' },
            { name: 'Novi Sad', desc: 'Multicultural city, Ottoman architecture' },
            { name: 'Novi Pazar', desc: 'Heart of Serbian Islamic culture & community' },
        ],
        waMsg: "Assalamu'alaikum%20Maqna.ID%2C%20saya%20tertarik%20paket%20Serbia",
        emailSubject: 'Inquiry: Serbia Tour',
    },
    sriwijaya: {
        slug: 'sriwijaya',
        metaTitle: 'Sriwijaya Kingdom Heritage Tour — Maqna.ID',
        metaDesc: 'Explore the remnants of Southeast Asia\'s greatest empire. Inbound tour through Palembang, Jambi & Lampung discovering ancient Islamic heritage.',
        category: 'inbound',
        badge: 'Inbound Tour',
        image: CDN + 'sriwijaya.jpeg',
        imgAlt: 'Muaro Jambi Temple — Sriwijaya Kingdom Heritage',
        duration: 'Multi-Day',
        dest: 'Indonesia · Sumatera',
        title: 'Sriwijaya Kingdom Heritage',
        sub: 'Ancient Maritime Empire',
        desc: 'Explore the remnants of one of Southeast Asia\'s greatest empires. Discover ancient temples, maritime history, and the spiritual foundation of Islamic heritage.',
        highlights: ['Muaro Jambi Archaeological Complex', 'Palembang — Ancient Capital', 'Museum Sultan Mahmud Badaruddin II', 'Ampera Bridge & Musi River', 'Islamic Sultanate Heritage Trail', 'Lampung Cultural Villages'],
        includes: ['Ground transport from Jakarta/Bogor', 'Hotel accommodation throughout', 'Halal meals included', 'Maqna.ID guide & local expert', 'All entrance fees & activities'],
        info: [{ label: 'Region', value: 'Sumatera' }, { label: 'Season', value: 'Year-round' }, { label: 'Type', value: 'Heritage' }, { label: 'Country', value: 'Indonesia' }],
        route: [
            { name: 'Palembang', desc: 'Sriwijaya capital, Musi River, historic sites' },
            { name: 'Jambi', desc: 'Muaro Jambi complex — largest Buddhist temple in Southeast Asia' },
            { name: 'Lampung', desc: 'Cultural exploration & final reflection' },
        ],
        waMsg: "Assalamu'alaikum%20Maqna.ID%2C%20saya%20tertarik%20paket%20Sriwijaya",
        emailSubject: 'Inquiry: Sriwijaya Heritage Tour',
    },
    bogor: {
        slug: 'bogor',
        metaTitle: 'Inspiring Bogor Islamic Learning Tour — Maqna.ID',
        metaDesc: 'Journey through West Java\'s rich heritage. Explore Bogor, Bandung & Sukabumi — centers of Islamic learning and natural wonders.',
        category: 'inbound',
        badge: 'Inbound Tour',
        image: CDN + 'bogor.jpeg',
        imgAlt: 'Bogor West Java — Rice Fields & Mountains',
        duration: 'Multi-Day',
        dest: 'Indonesia · West Java',
        title: 'Inspiring Bogor',
        sub: 'Islamic Learning Hub',
        desc: 'Journey through West Java\'s significant sites from colonial history to natural wonders. Understand how this region became a center of Islamic learning.',
        highlights: ['Bogor Botanical Garden UNESCO', 'Bogor Palace Colonial Heritage', 'Islamic Learning Centers', 'Bandung Creative City', 'Sukabumi Geopark', 'West Java Culinary Experience'],
        includes: ['Ground transport throughout', 'Hotel accommodation', 'Halal meals included', 'Maqna.ID guide & local expert', 'All entrance fees & activities'],
        info: [{ label: 'Region', value: 'West Java' }, { label: 'Season', value: 'Year-round' }, { label: 'Type', value: 'Cultural' }, { label: 'Country', value: 'Indonesia' }],
        route: [
            { name: 'Bogor', desc: 'Botanical Garden, Palace, Islamic learning centers' },
            { name: 'Bandung', desc: 'Creative city, heritage sites, colonial architecture' },
            { name: 'Sukabumi', desc: 'Geopark Ciletuh, natural wonders & reflection' },
        ],
        waMsg: "Assalamu'alaikum%20Maqna.ID%2C%20saya%20tertarik%20paket%20Inspiring%20Bogor",
        emailSubject: 'Inquiry: Inspiring Bogor Tour',
    },
    baduy: {
        slug: 'baduy',
        metaTitle: 'Inner Baduy Adventure Tour — Maqna.ID',
        metaDesc: 'Meet the Inner Baduy people and experience their traditional way of life. Indigenous wisdom journey through Banten, Indonesia.',
        category: 'inbound',
        badge: 'Adventure Tour',
        image: CDN + 'baduy.jpeg',
        imgAlt: 'Inner Baduy Village — Banten',
        duration: 'Multi-Day',
        dest: 'Indonesia · Banten',
        title: 'Inner Baduy Adventure',
        sub: 'Indigenous Wisdom',
        desc: 'Meet the Inner Baduy people and experience their traditional way of life. A rare opportunity to understand indigenous wisdom and spiritual practices.',
        highlights: ['Trek into Inner Baduy Territory', 'Baduy Community Leaders', 'Traditional Weaving & Crafts', 'Ciboletes River Trekking', 'Indigenous Wisdom Sessions', 'Rangkasbitung Heritage'],
        includes: ['Ground transport from Jakarta/Bogor', 'Accommodation & camping equipment', 'All meals (field rations & local cuisine)', 'Maqna.ID guide & local Baduy liaison', 'All trekking permits & fees'],
        info: [{ label: 'Region', value: 'Banten' }, { label: 'Season', value: 'Dry Season' }, { label: 'Type', value: 'Adventure' }, { label: 'Country', value: 'Indonesia' }],
        route: [
            { name: 'Rangkasbitung', desc: 'Departure point, heritage sites & preparation' },
            { name: 'Outer Baduy', desc: 'Community visit & cultural introduction' },
            { name: 'Inner Baduy', desc: 'Trek into the heart of Baduy territory' },
            { name: 'Ciboletes', desc: 'River trek & final reflections' },
        ],
        waMsg: "Assalamu'alaikum%20Maqna.ID%2C%20saya%20tertarik%20paket%20Inner%20Baduy",
        emailSubject: 'Inquiry: Inner Baduy Adventure Tour',
    },
};
